
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{.Values.deployment.strategy.maxSurge}}
      maxUnavailable: {{.Values.deployment.strategy.maxUnavailable}}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      initContainers:
        - name: copy-config
          image: nginx:1.19
          command:
            - sh
            - -c
            - envsubst < /config-init/config.json > /srv/src/enketo_express/config/config.json
          volumeMounts:
            - name: {{ include "app.fullname" . }}-config
              mountPath: "/config-init/config.json"
              subPath: config.json
            - name: {{ include "app.fullname" . }}-cache-volume
              subPath: config
              mountPath: "/srv/src/enketo_express/config"
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}

      containers:
        - name: nginx-{{ include "app.fullname" . }}
          image: nginx:1.19
          ports:
          - containerPort: {{ .Values.service.app.containerPort }}
          volumeMounts:
          - name: {{ include "app.fullname" . }}-init-kobo-nginx
            mountPath: "/docker-entrypoint.d/30-init-kobo-nginx.sh"
            subPath: 30-init-kobo-nginx.sh
          - name: {{ include "app.fullname" . }}-https-redirection-conf
            mountPath: "/kobo-docker-scripts/templates/include.https_redirection.conf.tmpl"
            subPath: include.https_redirection.conf.tmpl
          - name: {{ include "app.fullname" . }}-maintenance-default-conf
            mountPath: "/kobo-docker-scripts/templates/maintenance_default.conf.tmpl"
            subPath: maintenance_default.conf.tmpl
          - name: {{ include "app.fullname" . }}-nginx-site-default-conf
            mountPath: "/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl"
            subPath: nginx_site_default.conf.tmpl
          - name: {{ include "app.fullname" . }}-proxy-pass-conf
            mountPath: "/kobo-docker-scripts/templates/proxy_pass.conf.tmpl"
            subPath: proxy_pass.conf.tmpl
          - name: {{ include "app.fullname" . }}-uwsgi-pass-conf
            mountPath: "/kobo-docker-scripts/templates/uwsgi_pass.conf.tmpl"
            subPath: uwsgi_pass.conf.tmpl
          - name: {{ include "app.fullname" . }}-server-directive-common-conf
            mountPath: "/kobo-docker-scripts/include.server_directive_common.conf"
            subPath: include.server_directive_common.conf
          - name: {{ include "app.fullname" . }}-nginx-conf
            mountPath: "/kobo-docker-scripts/nginx.conf"
            subPath: nginx.conf
          

          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}

        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8005
          volumeMounts:
          - name: {{ include "app.fullname" . }}-cache-volume
            subPath: config/config.json
            mountPath: "/srv/src/enketo_express/config/config.json"
          - name: {{ include "app.fullname" . }}-icons
            mountPath: "/srv/src/enketo_express/public/images/"
          - name: {{ include "app.fullname" . }}-cache-volume
            mountPath: /srv/src/enketo_express/checksum
            subPath: checksum
          - name: {{ include "app.fullname" . }}-cache-volume
            mountPath: /srv/src/enketo_express/public/css
            subPath: build/css
          - name: {{ include "app.fullname" . }}-cache-volume
            mountPath: /srv/src/enketo_express/public/js/build
            subPath: build/js
          - name: {{ include "app.fullname" . }}-cache-volume
            mountPath: /srv/src/enketo_express/locales/build
            subPath: build/locales
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
          resources:
            {{- toYaml .Values.resources.kc | nindent 12 }}

      volumes:
        - name: {{ include "app.fullname" . }}-init-kobo-nginx
          configMap:
            name: {{ include "app.fullname" . }}-init-kobo-nginx
            defaultMode: 0755
        - name: {{ include "app.fullname" . }}-https-redirection-conf
          configMap:
            name: {{ include "app.fullname" . }}-https-redirection-conf
        - name: {{ include "app.fullname" . }}-maintenance-default-conf
          configMap:
            name: {{ include "app.fullname" . }}-maintenance-default-conf
        - name: {{ include "app.fullname" . }}-nginx-site-default-conf
          configMap:
            name: {{ include "app.fullname" . }}-nginx-site-default-conf
        - name: {{ include "app.fullname" . }}-proxy-pass-conf
          configMap:
            name: {{ include "app.fullname" . }}-proxy-pass-conf
        - name: {{ include "app.fullname" . }}-uwsgi-pass-conf
          configMap:
            name: {{ include "app.fullname" . }}-uwsgi-pass-conf
        - name: {{ include "app.fullname" . }}-server-directive-common-conf
          configMap:
            name: {{ include "app.fullname" . }}-server-directive-common-conf
        - name: {{ include "app.fullname" . }}-nginx-conf
          configMap:
            name: {{ include "app.fullname" . }}-nginx-conf
        - name: {{ include "app.fullname" . }}-icons
          configMap:
            name: {{ include "app.fullname" . }}-icons
        - name: {{ include "app.fullname" . }}-config
          secret:
            secretName: {{ include "app.fullname" . }}-config
        - name: {{ include "app.fullname" . }}-cache-volume
          emptyDir: {}

---
