---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-icons
data:
  favicon.ico: |
    {{ (.Files.Glob "config/enketo_express/favicon.ico").AsConfig | indent 2 }}
  icon_180x180.png: |
    {{ (.Files.Glob "config/enketo_express/icon_180x180.png").AsConfig | indent 2 }}
