---
apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "app.fullname" . }}-config
stringData:
  config.json: |-
    {
      "app name": "Enketo Express for KoBo Toolbox",
      "encryption key": "$ENKETO_ENCRYPTION_KEY",
      "google": {
          "analytics": {
              "domain": "$ENKETO_EXPRESS_PUBLIC_SUBDOMAIN.$PUBLIC_DOMAIN_NAME",
              "ua": ""
          },
          "api key": "$GOOGLE_ANALYTICS_TOKEN"

      },
      "less secure encryption key": "this $3cr3t key is crackable",
      "linked form and data server": {
          "api key": "$ENKETO_API_KEY",
          "name": "KoBo Toolbox",
          "server url": ""
      },
      "maps": [
          {
              "attribution": "&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> & <a href=\"https://www.hotosm.org/updates/2013-09-29_a_new_window_on_openstreetmap_data\">Yohan Boniface & Humanitarian OpenStreetMap Team</a> | <a href=\"https://www.openstreetmap.org/copyright\">Terms</a>",
              "name": "humanitarian",
              "tiles": [
                  "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"
              ]
          },
          {
              "attribution": "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
              "name": "satellite",
              "tiles": [
                  "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
              ]
          },
          {
              "attribution": "&copy; <a href=\"https://openstreetmap.org\">OpenStreetMap</a> | <a href=\"https://www.openstreetmap.org/copyright\">Terms</a>",
              "name": "terrain",
              "tiles": [
                  "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"
              ]
          },
          {
              "attribution": "&copy; <a href=\"https://openstreetmap.org\">OpenStreetMap</a> | <a href=\"https://www.openstreetmap.org/copyright\">Terms</a>",
              "name": "streets",
              "tiles": [
                  "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              ]
          }
      ],
      "payload limit": "1mb",
      "redis": {
          "cache": {
              "host": "$REDIS_CACHE_HOST",
              "password": "$REDIS_PASSWORD",
              "port": "6379"
          },
          "main": {
              "host": "$REDIS_MAIN_HOST",
              "password": "$REDIS_PASSWORD",
              "port": "6379"
          }
      },
      "support": {
          "email": "$KOBO_SUPPORT_EMAIL"
      },
      "text field character limit": 1000000,
      "widgets": [
          "note",
          "select-desktop",
          "select-mobile",
          "autocomplete",
          "geo",
          "textarea",
          "url",
          "table",
          "radio",
          "date",
          "time",
          "datetime",
          "select-media",
          "file",
          "draw",
          "rank",
          "likert",
          "range",
          "columns",
          "image-view",
          "comment",
          "image-map",
          "date-native",
          "date-native-ios",
          "date-mobile",
          "text-max",
          "text-print",
          "rating",
          "thousands-sep",
          "../../../node_modules/enketo-image-customization-widget/image-customization",
          "../../../node_modules/enketo-literacy-test-widget/literacywidget"
      ]
    }
